# Run with: docker compose -p hpc_flask_test -f docker-compose.yml -f docker-compose.test.yml run --rm app_test
services:
  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hpc_test
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hpc_test"]
      interval: 2s
      timeout: 2s
      retries: 30

  app_test:
    build: .
    depends_on:
      db_test:
        condition: service_healthy
    environment:
      APP_ENV: test
      # Point the app to the test DB
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db_test:5432/hpc_test
      # Anything else your app uses at boot
      AUTO_CREATE_SCHEMA: "1"
      METRICS_ENABLED: "0"
      COPILOT_ENABLED: "0"
      FLASK_SECRET_KEY: devtest
    command: ["pytest", "-q", "--maxfail=1", "--disable-warnings", "-ra"]
    volumes:
      - ./:/app
