site_name: HPC Billing Platform Docs

theme:
  name: material

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight

plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Quickstart: getting-started.md
  - Requirements (SRS): 01-srs.md
  - Concepts:
      - Architecture: 02-architecture.md
      - Data Model (ERD): 03-data-model.md
      - Costing & Pricing Model: 03b-pricing.md
      - Accounting & Compliance (IFRS/TFRS, VAT, ECL): 03c-accounting.md
      - Security & Audit (HMAC chain): 06-security.md
      - Privacy: 11-privacy.md
  - Guides:
      - User Guide: 17-usage.md
      - Admin Guide: 17b-admin-guide.md
      - API (OpenAPI + Swagger): 04-api.md
      - LLM Copilot (in-app help/RAG): 04b-copilot.md
  - Operations:
      - Deployment: 07-deployment.md
      - Configuration Reference (env & flags): 07b-config.md
      - Operations (jobs, billing runs): 08-ops.md
      - Backup & Restore: 08b-backup.md
      - Upgrades & Migrations: 08c-migrations.md
  - Testing & Quality:
      - Testing: 09-testing.md
      - Performance: 10-performance.md
      - Metrics: 13-metrics.md
  - Integrations & Exports:
      - Slurm Data Sources: 05-flows.md
      - e-Tax / GL Export: 12-etax-export.md
  - Troubleshooting: 15-trouble.md
  - Glossary: 16-glossary.md
  - Roadmap: 14-roadmap.md
  - Changelog: 99-changelog.md
