openapi: 3.0.3
info:
  title: HPC Billing Platform API
  version: 0.2.0
  description: |
    Minimal JSON/CSV endpoints used by the app and admin tools. Online payments
    webhook is **not exposed** in this build. Admin marks paid manually.
servers:
  - url: http://localhost:8000
    description: Dev (Flask in Docker)

tags:
  - name: Health
  - name: Rates
  - name: Metrics
  - name: Audit
  - name: Ledger
  - name: Exports
  - name: Copilot

paths:
  /healthz:
    get:
      tags:
        - Health
      summary: Liveness check
      responses:
        200:
          description: App process is alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: "ok"

  /readyz:
    get:
      tags:
        - Health
      summary: Readiness check (DB connectivity)
      responses:
        200:
          description: DB reachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: "ok"
        500:
          description: DB not reachable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: "fail"
                reason: "db"

  /metrics:
    get:
      tags:
        - Metrics
      summary: Prometheus metrics (text/plain)
      responses:
        200:
          description: Prometheus exposition format
          content:
            text/plain:
              schema:
                type: string
                description: Prometheus text exposition

  /formula:
    get:
      tags:
        - Rates
      summary: Get current pricing formula (tiers and rates)
      parameters:
        - name: If-None-Match
          in: header
          required: false
          schema:
            type: string
          description: Send a prior ETag to receive **304 Not Modified** if unchanged.
      responses:
        200:
          description: Current tier rates
          headers:
            ETag:
              description: Strong ETag of the current formula
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RateResponse"
        304:
          description: Unchanged since the ETag provided

    post:
      tags:
        - Rates
      summary: Update pricing formula (admin only)
      security:
        - cookieAuth: []
        - xsrfToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/RateUpdateOne"
                - $ref: "#/components/schemas/RateUpdateBulk"
            examples:
              single:
                summary: Update a single tier
                value:
                  tier: gov
                  cpu: 3.5
                  gpu: 10.0
                  mem: 1.0
              bulk:
                summary: Update multiple tiers
                value:
                  tiers:
                    - tier: mu
                      cpu: 0.02
                      gpu: 1.50
                      mem: 0.001
                    - tier: gov
                      cpu: 0.03
                      gpu: 2.00
                      mem: 0.002
      responses:
        200:
          description: Updated formula
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RateResponse"
        401:
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        403:
          description: Not authorized (admin required)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"

  /admin/audit.verify.json:
    get:
      tags:
        - Audit
      summary: Verify audit HMAC chain
      security:
        - cookieAuth: []
      responses:
        200:
          description: Verification result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuditVerifyResponse"

  /admin/ledger.csv:
    get:
      tags:
        - Ledger
      summary: Export derived journal (CSV)
      security:
        - cookieAuth: []
      responses:
        200:
          description: CSV stream of derived (preview) journal entries
          content:
            text/csv:
              schema:
                type: string

  /admin/export/ledger.csv:
    get:
      tags:
        - Exports
      summary: Export posted GL (CSV)
      security:
        - cookieAuth: []
      responses:
        200:
          description: CSV stream of posted GL entries
          content:
            text/csv:
              schema:
                type: string

  /admin/export/gl/formal.zip:
    post:
      tags:
        - Exports
      summary: Create signed formal GL ZIP (manifest + HMAC)
      security:
        - cookieAuth: []
        - xsrfToken: []
      responses:
        200:
          description: ZIP file
          content:
            application/zip:
              schema:
                type: string
                format: binary

  /copilot/widget.js:
    get:
      tags:
        - Copilot
      summary: Load embeddable widget JS (public)
      responses:
        200:
          description: JavaScript
          content:
            application/javascript:
              schema:
                type: string

  /copilot/ask:
    post:
      tags:
        - Copilot
      summary: Ask a question (CSRF-exempt; rate-limited)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CopilotAskRequest"
      responses:
        200:
          description: Answer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CopilotAskResponse"

  /copilot/reindex:
    post:
      tags:
        - Copilot
      summary: Rebuild docs index (admin)
      security:
        - cookieAuth: []
        - xsrfToken: []
      responses:
        200:
          description: Reindex started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
    xsrfToken:
      type: apiKey
      in: header
      name: X-CSRFToken

  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
        reason:
          type: string
          nullable: true

    Problem:
      type: object
      properties:
        code:
          type: integer
        error:
          type: string
        detail:
          type: string
      required:
        - error

    RateTier:
      type: object
      properties:
        tier:
          type: string
          enum:
            - mu
            - gov
            - private
        cpu:
          type: number
        gpu:
          type: number
        mem:
          type: number
        updated_at:
          type: string
          format: date-time
      required:
        - tier
        - cpu
        - gpu
        - mem

    RateResponse:
      type: object
      properties:
        version:
          type: string
          format: date-time
        tiers:
          type: array
          items:
            $ref: "#/components/schemas/RateTier"
      required:
        - tiers

    RateUpdateOne:
      type: object
      properties:
        tier:
          type: string
          enum:
            - mu
            - gov
            - private
        cpu:
          type: number
        gpu:
          type: number
        mem:
          type: number
      required:
        - tier
        - cpu
        - gpu
        - mem

    RateUpdateBulk:
      type: object
      properties:
        tiers:
          type: array
          items:
            $ref: "#/components/schemas/RateUpdateOne"
      required:
        - tiers

    AuditVerifyResponse:
      type: object
      properties:
        ok:
          type: boolean
        checked:
          type: integer
          description: Number of rows verified
        break_index:
          type: integer
          nullable: true
        message:
          type: string
          nullable: true

    CopilotAskRequest:
      type: object
      properties:
        q:
          type: string
        top_k:
          type: integer
          minimum: 1
          maximum: 20
          default: 6
      required:
        - q

    CopilotAskResponse:
      type: object
      properties:
        answer:
          type: string
        tokens:
          type: integer
          nullable: true
        sources:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              score:
                type: number
              snippet:
                type: string
